name: Kubernetes deployment
on:
  push:
    branches:
      - main

env: 
  FRONTEND_IMAGE: roshankhadka50/3tier-frontend

  BACKEND_IMAGE: roshankhadka50/3tier-backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: create .env for client
      run: |
        echo "REACT_APP_API_URL=$44{{ secrets.API_URL}}" > application/client/.env

    - name: set up Docker Build
      uses: docker/setup-buildx-action@v3

    - name: login to DockerHub
      uses: docker/login-action@v3 
      with: 
        registry: docker.io 
        username: ${{ secrets.DOCKER_USER}}
        password: ${{ secrets.DOCKER_PASSWORD}}

    - name: Build and push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./application/client
        push: true
        tags: ${{ env.FRONTEND_IMAGE }}:latest


    - name: Build and push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./application/server
        push: true
        tags: ${{ env.BACKEND_IMAGE }}:latest